#!/usr/bin/env python3

#
# Copyright (C) 2024-2025 PyFPGA Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import argparse
import sys


parser = argparse.ArgumentParser()

parser.add_argument('source')

args = parser.parse_args()

tool = parser.prog

if not args.source.startswith("SCRIPT:", 0):
    print('ERROR:the parameter should start width "SCRIPT:"')
    sys.exit(1)

print(f'INFO:the {tool.upper()} mock has been executed')
