#!/usr/bin/env python3

#
# Copyright (C) 2022-2025 PyFPGA Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import argparse


parser = argparse.ArgumentParser()

parser.add_argument('-batch', action='store_true', required=True)
parser.add_argument('source')

args = parser.parse_args()

tool = parser.prog

print(f'INFO:the {tool.upper()} mock has been executed')
