#!/usr/bin/env python3

#
# Copyright (C) 2022-2024 PyFPGA Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import argparse
import re
import subprocess
import sys


parser = argparse.ArgumentParser()

parser.add_argument('source')

args = parser.parse_args()

tool = parser.prog

if not args.source.startswith("SCRIPT:", 0):
    print('ERROR:the parameter should start width "SCRIPT:"')
    sys.exit(1)

args.source = args.source.replace('SCRIPT:', '')

tcl = f'''
proc unknown args {{ }}

source {args.source}
'''

with open(f'{tool}-mock.tcl', 'w', encoding='utf-8') as file:
    file.write(tcl)

subprocess.run(
   f'tclsh {tool}-mock.tcl',
   shell=True,
   check=True,
   universal_newlines=True
)

pattern = r'new_project\s+-name\s+(\S+)\s'
with open(args.source, 'r', encoding='utf-8') as file:
    match = re.search(pattern, file.read())
    if match:
        project = match.group(1)
        with open(f'{project}.ppd', 'w', encoding='utf-8') as file:
            pass

print(f'INFO:the {tool.upper()} mock has been executed')
