#!/usr/bin/env python3

#
# Copyright (C) 2022-2024 PyFPGA Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import argparse
import os
import subprocess


parser = argparse.ArgumentParser()

parser.add_argument('--script', required=True)

args = parser.parse_args()

tool = parser.prog

tcl = f'''
proc unknown args {{ }}

package provide ::quartus::project 1.0
namespace eval ::quartus::project {{ }}

package provide ::quartus::flow 1.0
namespace eval ::quartus::flow {{ }}

source {args.script}
'''

with open(f'{tool}-mock.tcl', 'w', encoding='utf-8') as file:
    file.write(tcl)

subprocess.run(
   f'tclsh {tool}-mock.tcl',
   shell=True,
   check=True,
   universal_newlines=True
)

print(f'INFO:the {tool.upper()} mock has been executed')
