#!/usr/bin/env python3

#
# Copyright (C) 2022-2025 PyFPGA Project
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import argparse
import os
import re
import subprocess


parser = argparse.ArgumentParser()

parser.add_argument('--script', required=True)

args = parser.parse_args()

tool = parser.prog

tcl = f'''
proc unknown args {{ }}

package provide ::quartus::project 1.0
namespace eval ::quartus::project {{ }}

package provide ::quartus::flow 1.0
namespace eval ::quartus::flow {{ }}

source {args.script}
'''

with open(f'{tool}-mock.tcl', 'w', encoding='utf-8') as file:
    file.write(tcl)

subprocess.run(
   f'tclsh {tool}-mock.tcl',
   shell=True,
   check=True,
   universal_newlines=True
)

pattern = r'project_new\s+(\S+)\s'
with open(args.script, 'r', encoding='utf-8') as file:
    match = re.search(pattern, file.read())
    if match:
        project = match.group(1)
        open(f'{project}.sof', 'w', encoding='utf-8').close()

print(f'INFO:the {tool.upper()} mock has been executed')
