#!/usr/bin/env python3
#
# Copyright (C) 2022 Rodrigo A. Melo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse
import os
import subprocess


parser = argparse.ArgumentParser()

parser.add_argument('--script', required=True)

args = parser.parse_args()

tool = parser.prog

tcl = f'''
lappend auto_path pkg

proc unknown {{ cmmd args }} {{ }}

source {args.script}
'''

with open(f'{tool}-mock.tcl', 'w', encoding='utf-8') as file:
    file.write(tcl)

tcl = f'''
namespace eval ::quartus {{
  namespace export project
}}
'''

if not os.path.exists('pkg'):
    os.makedirs('pkg')

package ifneeded ::quartus 1.0 [list source quartus-pkg.tcl]

pkgIndex.tcl

with open(f'pkg/quartus.tcl', 'w', encoding='utf-8') as file:
    file.write(tcl)

subprocess.run(
   f'tclsh {tool}-mock.tcl',
   shell=True,
   check=True,
   universal_newlines=True,
   #stdout=output, stderr=subprocess.STDOUT
)

print(f'INFO:the {tool.upper()} mock has been executed')
