from pyfpga.vivado import Vivado


def test_vivado():
    prj = Vivado()
    prj.set_part('PARTNAME')
    prj.set_top('TOPNAME')
    prj.set_arch('ARCHNAME')
    prj.add_include('fakedata/dir1')
    prj.add_include('fakedata/dir2')
    prj.add_slog('fakedata/**/*.sv')
    prj.add_vhdl('fakedata/**/*.vhdl', 'LIB')
    prj.add_vlog('fakedata/**/*.v')
    prj.add_cons('fakedata/cons/all.xdc')
    prj.add_cons('fakedata/cons/syn.xdc', 'syn')
    prj.add_cons('fakedata/cons/par.xdc', 'par')
    prj.add_param('PAR1', 'VAL1')
    prj.add_param('PAR2', 'VAL2')
    prj.add_define('DEF1', 'VAL1')
    prj.add_define('DEF2', 'VAL2')
    prj.add_hook('precfg', 'PRECFG_HOOK')
    prj.add_hook('postcfg', 'POSTCFG_HOOK')
    prj.add_hook('presyn', 'PRESYN_HOOK')
    prj.add_hook('postsyn', 'POSTSYN_HOOK')
    prj.add_hook('prepar', 'PREPAR_HOOK')
    prj.add_hook('postpar', 'POSTPAR_HOOK')
    prj.add_hook('prebit', 'PREBIT_HOOK')
    prj.add_hook('postbit', 'POSTBIT_HOOK')
    prj.make()
