from pyfpga.vivado import Vivado


def test_vivado():
    prj = Vivado()

    prj.set_arch('ARCHNAME')
    prj.add_include('fakedata/dir1')
    prj.add_include('fakedata/dir2')
    prj.add_param('PARAM1', 'VALUE1')
    prj.add_param('PARAM2', 'VALUE2')
    prj.add_define('DEFINE1', 'VALUE1')
    prj.add_define('DEFINE2', 'VALUE2')
    prj.add_hook('precfg', 'HOOK1')
    prj.add_hook('precfg', 'HOOK1')
    prj.add_hook('postcfg', 'HOOK2')
    prj.add_hook('postcfg', 'HOOK2')
    prj.add_hook('presyn', 'HOOK3')
    prj.add_hook('presyn', 'HOOK3')
    prj.add_hook('postsyn', 'HOOK4')
    prj.add_hook('postsyn', 'HOOK4')
    prj.add_hook('prepar', 'HOOK5')
    prj.add_hook('prepar', 'HOOK5')
    prj.add_hook('postpar', 'HOOK6')
    prj.add_hook('postpar', 'HOOK6')
    prj.add_hook('prebit', 'HOOK7')
    prj.add_hook('prebit', 'HOOK7')
    prj.add_hook('postbit', 'HOOK8')
    prj.add_hook('postbit', 'HOOK8')
    prj.make()
