openflow:
    oci:
        engine:
            command: docker
            volumes: ["$HOME:$HOME"]
            work: $PWD
        containers:
            ghdl: "ghdl/synth:beta"
            yosys: "ghdl/synth:beta"
            nextpnr-ice40: "ghdl/synth:nextpnr-ice40"
            icetime: "ghdl/synth:icestorm"
            icepack: "ghdl/synth:icestorm"
            iceprog: "--device /dev/bus/usb ghdl/synth:prog"
            nextpnr-ecp5: "ghdl/synth:nextpnr-ecp5"
            ecppack: "ghdl/synth:trellis"
            openocd: "--device /dev/bus/usb ghdl/synth:prog"
    tools:
        ghdl: ghdl
        yosys: yosys
        nextpnr-ice40: nextpnr-ice40
        icetime: icetime
        icepack: icepack
        iceprog: iceprog
        nextpnr-ecp5: nextpnr-ecp5
        ecppack: ecppack
        openocd: openocd
