#!/usr/bin/env python3
#
# Copyright (C) 2022 Rodrigo A. Melo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('-c', required=True)
parser.add_argument('--mode', choices=['jtag'], required=True)
parser.add_argument('-o', required=True)

args = parser.parse_args()

print(f'INFO:the {parser.prog.upper()} mock has been executed')
