image: python:latest

before_script:
  - python -V

stages:
  - build
  - pages

build:
  stage: build
  script:
    - cd doc
    - pip install -r requirements.txt
    - mkdir _theme
    - curl -fsSL https://codeload.github.com/buildthedocs/sphinx.theme/tar.gz/v0 | tar xzf - -C _theme --strip-components=1
    - PYTHONPATH=$(pwd)/.. make html
  artifacts:
    paths:
      - doc/_build/html

pages:
  stage: pages
  script:
    - mv doc/_build/html public
  artifacts:
    paths:
      - public
  only:
    - master
