image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install .

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip install pycodestyle
    - pip install pylint
    - pycodestyle fpga examples test
    - pylint fpga
    - git diff --check --cached

test:
  stage: test
  needs: [ lint ]
  script:
    - pip install pytest
    - pytest
    - make -C examples
