name: 'doc'

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buildthedocs/btd@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@master
      with:
        name: doc
        path: doc/_build/html
