name: 'docs'

on:
  push:
    paths:
      - 'docs/**'
      - 'pyfpga/project.py'
    branches:
      - main
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install . && pip install sphinx sphinx-rtd-theme
    - name: Build documentation
      run: make docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
