name: 'test'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull container images
      run: |
        docker pull hdlc/ghdl:yosys
        docker pull hdlc/nextpnr:ice40
        docker pull hdlc/nextpnr:ecp5
        docker pull hdlc/icestorm
        docker pull hdlc/prjtrellis
    - name: Set up Python ${{ matrix.pyver }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyver }}
    - name: Install dependencies
      run: |
        pip install pytest
        pip install .
    - name: Run test
      run: pytest
    - name: Run examples
      run: |
        cd examples; make MOCKS=1
